### PR TITLE
Fix argument parsing for --attachment

### PR DESCRIPTION
**Pull request by mistralol**
When run with "--attachment=file" it works.
When running with "--attachment=file1 --attachment=file2" it would fail with an error "attachment expects a value" as the type is object instead of string.

### CODE REVIEW

**Comment by fardog** [comment]
@mistralol possible to get a test added for this fix?

**Comment by mistralol** [comment]
I will try but its not likly to be for a few days. I have another probably patch coming as well for "silence" on success. So just leave this sitting for the minute.

**Comment by fardog** [comment]
@mistralol thanks for adding tests to this; is this ready to merge? if so, I'll merge and release as v2.1.0

thanks!

**Comment by mistralol** [comment]
Yes it should be good to go. I also ran some other checks on it to make sure I didn't break things

**Pull request merged**
