### PR TITLE
Some more changes

### PR DESCRIPTION
**Pull request by mistralol**
Hi,

I added a few more changes that brings the packages up to date. It runs the tests on my machine. Some of these probably still need updated.

Fixed a bug with the server alias being missing in the command line parsing.

I added -N (--notls) which disabled TLS if -n (--nossl) is being used. Nodemailer wants to fall back to this. TLS.

Nodemailer currently also has a bug where it cannot correctly validate the TLS cert. So I also added an option to ignore the certificate. -i (--ignorecert). This may be confusing since SSL isn't verified the same way.

### CODE REVIEW

**Comment by mistralol** [comment]
BTW. That test doesn't seem to fail on node v6.7.0

**Comment by fardog** [comment]
I think this looks fine; would like to see the following:

- please update `.travis.yml` for modern node (should be 4 and 6) that way we don't fail travis tests
- please add `"engines": { "node": ">=4" }` to the `package.json`; this will ensure anyone that installs it on an older, unsupported version of node.js receives a warning.

Once this is merged in, I'll release this as version 2.0, so that folks on older node.js versions can continue to use the 1.x series if necessary.

**Comment by fardog** [comment]
(also if you don't have the chance, I can go ahead and merge this and make those changes myself; just let me know. thank you!)

**Comment by mistralol** [comment]
Updated pull request bumped version numbers to 2.0.0 and bumped node base version to 4.0.0

**Pull request merged**
